### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by MV487** [Ajaykumar415/space-pew-pew-#1]
hi, i am having an issue running your GAME!
pygame 2.0.0 (SDL 2.0.12, python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\User\Documents\GitHub\space-pew-pew-\main.py", line 11, in <module>
    icon = pygame.image.load('icon.png')
FileNotFoundError: No such file or directory.

please assist me.

**Comment by Ajaykumar415** [comment]
fixed it right now, lol
